### ISSUE TITLE
update documentation to include javascript, and css references

### ISSUE THREAD

**Issue by ntregillus** [emalikterzi/angularjs-daterangepicker#2]
examples in readme do not show that this library depends upon the original jquery datepicker, and that it has to be referenced.

**Comment by emalikterzi** [comment]
there is a link in readme. it's refering to orjinal datepicker site . @ntregillus

**Comment by ntregillus** [comment]
Sorry, my original ask was not too clear.
The example is listing html, but does not include where to link the javascript and css within the page. that would be clearer that the date-picker is not a standalone module, but rather requires a reference to the jquery plugin.

**Comment by stereokai** [comment]
@emalikterzi, @ntregillus is right! Please fix this..
